
#include "lawd/error.h"

void law_err_init()
{
        SEL_BIND(LAW_ERR_TRY_AGAIN, "LAW_ERR_TRY_AGAIN");
        SEL_BIND(LAW_ERR_BAD_MODE, "LAW_ERR_BAD_MODE");
        SEL_BIND(LAW_ERR_ENCOUNTERED_EOF, "LAW_ERR_ENCOUNTERED_EOF");
        SEL_BIND(LAW_ERR_SOCKET_IO, "LAW_ERR_SOCKET_IO");
        SEL_BIND(LAW_ERR_MALFORMED_MESSAGE, "LAW_ERR_MALFORMED_MESSAGE");
        SEL_BIND(LAW_ERR_METHOD_NOT_ALLOWED, "LAW_ERR_METHOD_NOT_ALLOWED");
        SEL_BIND(LAW_ERR_UNSUPPORTED_VERSION, "LAW_ERR_UNSUPPORTED_VERSION");
}